export const ACTION_TYPES = {
  APP_SELECTED: 'APP_SELECTED',
  SELECTED_APP: 'SELECTED_APP',
  FULL_ACCESS: 'FULL_ACCESS',
  SELECTED_VARIANT: 'SELECTED_VARIANT',
  LOGGED_USER: 'LOGGED_USER',
  SHOW_MENU: 'SHOW_MENU',
  LOGOUT: 'LOGOUT',
AWS_USER_DATA: 'AWS_USER_DATA'
}