export const LANGUAGES = {
  "EN": {
    "building_a": "Building a",
    "sustainable": "Sustainable",
    "future": "Future",
    "enter_with_passcode": "Enter with Passcode",
    "enter_as_guest": "Enter as a Guest",
    "welcome": "Welcome !",
    "enter_passcode_to_access": "Enter your email address and passcode to access",
    "fill_in_details": "Enter your details below to gain access to consumers insights and explore the world of natural colors through augmented reality",
    "back": "Back",
    "name": "Name",
    "email": "Email",
    "submit": "Submit",
    "passcode": "Passcode",
    "phone": "Phone no.",
    "position": "Position",
    "company": "Company",
    "country": "Country",
    "interested_apps": "Key Areas of Interest",
    "i_agree_to": "I agree to the",
    "privacy_policy": "Privacy Policy",
    "applications": "Applications",
    "language": "Language",
    "next": "Next",
    "beverage": "Beverage",
    "confectionary": "Confectionery",
    "dairy_n_fruit": "Dairy & Fruit Preparation",
    "ice_creme": "Ice Cream",
    "bakery_n_cereals": "Bakery & Cereals",
    "savory_n_meat": "Savory & Meat",
    "plant_based": "Plant-based",
    "pet_food": "Pet Food",
    "none": "None",
    "consumer": "Consumer",
    "emotion": "Emotion",
    "flavor": "Flavor",
    "intensity": "Intensity",
    "solution": "Solution",
    "choose_app": "Choose one application",
    "burger_bun": "Burger Bun",
    "dumpling": "Dumpling",
    "puff_snacks": "Puff Snacks",
    "noodle": "Noodle",
    "burger_sauce": "Burger Sauce",
    "salad_dressing": "Salad Dressing",
    "savory_dip": "Savory Dip",
    "nugget": "Nugget",
    "potato_chip": "Potato Chip",
    "french_fries": "French Fries",
    "click_to_select_app": "Click to select from full list of applications",
    "consumer_persona": "Consumer Persona",
    "to_enjoy_ar_title": "To enjoy the augmented reality experience, please follow these simple steps:",
    "maintain_good_lighting": "Maintain good lighting",
    "avoid_direct_sunlight": "Avoid direct sunlight",
    "avoid_cluttered_space": "Avoid cluttered spaces",
    "keep_two_feet_distance": "Keep at least 2 feet of distance",
    "consumers_who_find": "Consumers who find",
    "appealing_text": "`appealing also show great interest to trying out savory foods in this color. They are usually females and see themselves as very adventurous when it come to trying unfamiliar food. When it comes to priorities regarding food, they enjoy culinary exploration and trying new flavours, cuisines and ingredients.`",
    "top_5_emotions": "Top five Emotions consumers associate with this color",
    "color_n_flovor": "Color and Flavor Intensity",
    "color_intensity": "Color Intensity",
    "consumer_rank": "30% of global consumers rank",
    "top_3_preferred_color": "as their top 3 most preferred color that will interest them the most to buy if they are looking for a novel or experimental food experience.",
    "they_associate": "They associate",
    "color_savory_food": "colored savory food to beetroot, strawberry, chilli, red dragonfruit and raspberry flavours.",
    "get_full_access": "Get Full Access",
    "contact_us": "Contact Us",
    "logout": "Logout",
    "choose_your_language": "Choose your preferred language",
    "confirm": "Confirm",
    "please_fill_out_form": "Please fill out the form below to gain full access to consumer insights and help us better meet your needs.",
    "full_access_ques1": "Are you currently using natural colors?",
    "full_access_ques2": "Do you have interest to use natural colors in your products?",
    "full_access_ques3": "Are you looking for an alternative natural color supplier?",
    "full_access_ques4": "What are your areas of interests? Select all that applies.",
    "full_access_ques5": "What challenges are you facing at the moment? Select all that applies.",
    "yes": "Yes",
    "no": "No",
    "new_product_ideas": "New product ideas",
    "color_solutions": "Color solutions that can offer unique shades",
    "market_trends": "`Market trends & consumers' insights Replacing artificial colors with natural colors Stability and shelf life of natural colors`",
    "value_to_brand": "How natural colors can value-add to your brand",
    "other": "Others (Please Specify)",
    "type_here": "Type Here",
    "do_not_know_about_colors": "I do not know anything about natural colors",
    "need_help_about_colors": "I need technical help with using natural colors",
    "need_help_with_compliance": "I need help with regulatory compliance across markets How to choose a color that appeals to consumers and meets flavor expectations",
    "need_market_and_consumers": "I need market and consumers insights to help me with my business decisions",
    "appealing": "Appealing",
    "neutral": "Neutral",
    "unappealing": "Unappealing",
    "home": "Home",
    "full_access_thank_you": "Thank you for your interest. Our experts will be in touch soon. Meanwhile, please check your email for a passcode.",
    "please_wait": "Please wait"
  },
  "CMN": {
    "building_a": "建设一个",
    "sustainable": "可持续的",
    "future": "未来",
    "enter_with_passcode": "使用密码输入",
    "enter_as_guest": "以访客身份进入",
    "welcome": "欢迎 ！",
    "enter_passcode_to_access": "输入您的电子邮件地址和密码进行访问",
    "fill_in_details": `-输入您的详细信息，以获取消费者洞察，并通过AR技
术探索自然色彩的世界`,
    "back": "后退",
    "name": "姓名",
    "email": "电子邮件",
    "submit": "提交",
    "passcode": "密码",
    "phone": "电话号码",
    "position": "位置",
    "company": "公司",
    "country": "国家",
    "interested_apps": "主要兴趣领域",
    "i_agree_to": "我同意",
    "privacy_policy": "隐私政策",
    "applications": "运用",
    "language": "语言",
    "next": "下一个",
    "beverage": "饮料",
    "confectionary": "糖果点心",
    "dairy_n_fruit": "乳制品和水果制备",
    "ice_creme": "冰淇淋",
    "bakery_n_cereals": "面包店和谷物",
    "savory_n_meat": "咸味和肉类",
    "plant_based": "植物性",
    "pet_food": "宠物食品",
    "none": "没有任何",
    "consumer": "消费者",
    "emotion": "情绪",
    "flavor": "味道",
    "intensity": "强度",
    "solution": "解决方案",
    "choose_app": "选择一个产品。",
    "burger_bun": "汉堡",
    "dumpling": "饺子",
    "puff_snacks": "膨化食品",
    "noodle": "面条",
    "burger_sauce": "汉堡酱",
    "salad_dressing": "沙拉酱",
    "savory_dip": "咸味蘸酱",
    "nugget": "炸鸡块",
    "potato_chip": "薯片",
    "french_fries": "薯条",
    "click_to_select_app": "点击从产品列表中选择。",
    "consumer_persona": "消费者个性。",
    "to_enjoy_ar_title": "为享受更好的AR体验，请：",
    "maintain_good_lighting": "保持良好的照明。",
    "avoid_direct_sunlight": "避免阳光直射。",
    "avoid_cluttered_space": "避免杂乱的背景。",
    "keep_two_feet_distance": "保持一定距离。",
    "consumers_who_find": "Consumers who find",
    "appealing_text": "`appealing also show great interest to trying out savory foods in this color. They are usually females and see themselves as very adventurous when it come to trying unfamiliar food. When it comes to priorities regarding food, they enjoy culinary exploration and trying new flavours, cuisines and ingredients.`",
    "top_5_emotions": "消费者被这种颜色所激发的情绪前5名",
    "color_n_flovor": "颜色和风味强度",
    "color_intensity": "颜色强度",
    "consumer_rank": "占全球消费者排名的30%",
    "top_3_preferred_color": "作为他们最喜欢的前 3 种颜色，如果他们正在寻找新颖或实验性的食物体验，那么他们最有兴趣购买。",
    "they_associate": "他们连接",
    "color_savory_food": "甜菜根、草莓、辣椒、红火龙果和覆盆子口味的多彩美味佳肴。",
    "get_full_access": "获得完整版。",
    "contact_us": "联系我们",
    "logout": "退出",
    "choose_your_language": "选择您喜欢的语言",
    "confirm": "确认",
    "please_fill_out_form": "输入您的详细信息，以获取消费者洞察，并通过AR技术探索自然色彩的世界",
    "full_access_ques1": "您目前使用的是天然色素吗？",
    "full_access_ques2": "您有兴趣在您的产品中使用天然色素吗？",
    "full_access_ques3": "您是否正在寻找替代的天然色素供应商？",
    "full_access_ques4": "你的兴趣领域是什么？选择所有适用的项。",
    "full_access_ques5": "您目前面临哪些挑战？选择所有适用的项。",
    "yes": "是",
    "no": "否",
    "new_product_ideas": "新产品创意",
    "color_solutions": "可以提供独特色调的色彩解决方案",
    "market_trends": "市场趋势和消费者洞察",
    "value_to_brand": "自然色彩如何为您的品牌增加价值",
    "other": "其他（请注明）",
    "type_here": "在此输入",
    "do_not_know_about_colors": "我不了解天然色素",
    "need_help_about_colors": "在应用天然色素方面我需要技术支持",
    "need_help_with_compliance": "I我需要跨国的法规支持", 
    "need_help_with_color_appeals": "如何选择吸引消费者并满足口味期望的颜色",
    "need_market_and_consumers": "我需要市场和消费者洞察来帮助我做出商业决策",
    "appealing": "吸引人的",
    "neutral": "中立",
    "unappealing": "不吸引力",
    "home": "家",
    "full_access_thank_you": "谢谢你的兴趣。 我们的专家很快就会联系。 同时，请检查您的电子邮件是否有通行码。"
  },
  "SPA": {
    "building_a": "Construyendo un",
    "sustainable": "Sostenible",
    "future": "Futuro",
    "enter_with_passcode": "Ingrese con contraseña",
    "enter_as_guest": "Entra como invitado",
    "welcome": "Bienvenido !",
    "enter_passcode_to_access":  `Introduzca sus datos a continuación para acceder a la
información de los consumidores y explorar el mundo de los colores naturales a través de la
realidad aumentada.`,
    "back": "Atrás",
    "name": "Nombre",
    "email": "Correo electrónico",
    "submit": "Entregar",
    "passcode": "Código de acceso",
    "phone": "Número de teléfono.",
    "position": "Puesto",
    "company": "Compañía",
    "country": "País",
    "interested_apps": "Áreas clave de interés",
    "i_agree_to": "Estoy de acuerdo con el",
    "privacy_policy": "política de privacidad",
    "applications": "Aplicaciones",
    "language": "Idioma",
    "next": "Próxima",
    "beverage": "Bebida",
    "confectionary": "Confitería",
    "dairy_n_fruit": "Preparación de lácteos y frutas",
    "ice_creme": "Helado",
    "bakery_n_cereals": "Panadería y Cereales",
    "savory_n_meat": "Salados y Carnes",
    "plant_based": "A base de plantas",
    "pet_food": "Comida para mascotas",
    "none": "Ninguno",
    "consumer": "CONSUMIDOR",
    "emotion": "EMOCIÓN",
    "flavor": "SABOR",
    "intensity": "INTENSIDAD",
    "solution": "SOLUCIÓN",
    "choose_app": "Elija una aplicación",
    "burger_bun": "PAN DE HAMBURGUESA",
    "dumpling": "DUMPLING",
    "puff_snacks": "SNACKS INFLADOS",
    "noodle": "FIDEOS",
    "burger_sauce": "SALSA DE HAMBURGUESA",
    "salad_dressing": "ADEREZO DE ENSALADA",
    "savory_dip": "SALSAS SALADAS",
    "nugget": "NUGGET DE POLLO",
    "potato_chip": "PAPAS FRITAS",
    "french_fries": "PAPAS A LA FRANCESA",
    "click_to_select_app": "Haga clic para seleccionar de la lista completa de aplicaciones",
    "consumer_persona": "Persona del consumidor",
    "to_enjoy_ar_title": "Para disfrutar de la experiencia de realidad aumentada, sigue estos sencillos pasos:",
    "maintain_good_lighting": "Mantener una buena iluminación",
    "avoid_direct_sunlight": "Evitar la luz solar directa",
    "avoid_cluttered_space": "Evitar espacios desordenados",
    "keep_two_feet_distance": "Mantener al menos 60 cm de distancia",
    "consumers_who_find": "Consumers who find",
    "appealing_text": "`appealing also show great interest to trying out savory foods in this color. They are usually females and see themselves as very adventurous when it come to trying unfamiliar food. When it comes to priorities regarding food, they enjoy culinary exploration and trying new flavours, cuisines and ingredients.`",
    "top_5_emotions": "Principales cinco emociones que los consumidores asocian con este color",
    "color_n_flovor": "Intensidad de color y sabor",
    "color_intensity": "Intensidad del color",
    "consumer_rank": "30% of global consumers rank",
    "top_3_preferred_color": "as their top 3 most preferred color that will interest them the most to buy if they are looking for a novel or experimental food experience.",
    "they_associate": "They associate",
    "color_savory_food": "colored savory food to beetroot, strawberry, chilli, red dragonfruit and raspberry flavours.",
    "get_full_access": "Acceso completo",
    "contact_us": "Contáctenos",
    "logout": "Cerrar sesión",
    "choose_your_language": "Elige tu idioma preferido",
    "confirm": "Confirmar",
    "please_fill_out_form": "Introduzca sus datos a continuación para acceder a la información de los consumidores y explorar el mundo de los colores naturales a través de la realidad aumentada.",
    "full_access_ques1": "¿Utiliza actualmente colores naturales?",
    "full_access_ques2": "¿Tiene interés en utilizar colores naturales en sus productos?",
    "full_access_ques3": "¿Está buscando un proveedor alternativo de colores naturales?",
    "full_access_ques4": "¿Cuáles son sus áreas de interés? Seleccione todas las que apliquen. Nuevas ideas de productos.",
    "full_access_ques5": "¿A qué retos se enfrenta actualmente? Seleccione todo lo que corresponda.",
    "yes": "Sí",
    "no": "No",
    "new_product_ideas": "Soluciones de color que puedan ofrecer tonos únicos",
    "color_solutions": "Tendencias del mercado y opiniones de los consumidores",
    "market_trends": "Sustitución de colorantes artificiales por naturales",
    "replace_color": "Reemplazo de colores artificiales por colores naturales.",
    "stability": "Estabilidad y vida útil de los colores naturales.",
    "value_to_brand": "Cómo los colores naturales pueden añadir valor a su marca",
    "other": "Otros (especifique):",
    "type_here": "Escribe aquí",
    "do_not_know_about_colors": "No sé nada sobre colores naturales",
    "need_help_about_colors": "Necesito ayuda técnica para utilizar colores naturales",
    "need_help_with_compliance": "Necesito ayuda para cumplir con la normativa en los distintos mercados",
    "need_help_choosing_color": "Cómo elegir un color que atraiga a los consumidores y satisfaga las expectativas de sabor",
    "need_market_and_consumers": `INecesito información sobre el mercado y los consumidores que me ayude
a tomar decisiones empresariales`,
    "appealing": "Atractivo",
    "neutral": "Neutro",
    "unappealing": "Poco apetecible",
    "home": "Inicio",
    "full_access_thank_you": "Gracias por su interés. Nuestros expertos se pondrán en contacto con usted en breve. Mientras tanto, por favor, compruebe su correo electrónico para un código de acceso."
  },
  "POR": {
    "building_a": "Construindo um",
    "sustainable": "Sustentável",
    "future": "Futura",
    "enter_with_passcode": "Entrar com código de acesso",
    "enter_as_guest": "Entrar como convidado",
    "welcome": "-Bem-vindo de volta!",
    "enter_passcode_to_access": "Introduza o seu endereço de correio eletrónico e a sua senha de acesso",
    "fill_in_details": "Entre com seus dados para ter acesso a informações de consumidores e explorar o mundo das cores naturais através da realidade aumentada",
    "back": "Voltar",
    "name": "Seu nome",
    "email": "Endereço de correio eletrónico",
    "submit": "Enviar",
    "passcode": "Código de acesso",
    "phone": "Número de telefone",
    "position": "Cargo",
    "company": "Empresa",
    "country": "País",
    "interested_apps": "Principais áreas de interesse",
    "i_agree_to": "Concordo com a",
    "privacy_policy": "Política de Privacidade",
    "applications": "Aplicações",
    "language": "Língua",
    "next": "Next",
    "beverage": "Bebida",
    "confectionary": "Confeitos",
    "dairy_n_fruit": "Lácteos e preparados de frutas",
    "ice_creme": "Sorvetes",
    "bakery_n_cereals": "Panificação e cereais",
    "savory_n_meat": "Salgados e carnes",
    "plant_based": "À base de plantas",
    "pet_food": "Alimentos para animais de estimação",
    "none": "Nenhum",
    "consumer": "CONSUMIDOR",
    "emotion": "EMOÇÃO",
    "flavor": "SABOR",
    "intensity": "INTENSIDADE",
    "solution": "SOLUÇÃO",
    "choose_app": "Escolha uma aplicação",
    "burger_bun": "PÃO DE HAMBÚRGUER",
    "dumpling": "Dumpling",
    "puff_snacks": "Salgadinhos",
    "noodle": "Noodle",
    "burger_sauce": "MOLHO PARA HAMBÚRGUER",
    "salad_dressing": "MOLHO PARA SALADA",
    "savory_dip": "Molho",
    "nugget": "Nugget",
    "potato_chip": "Batatas onduladas",
    "french_fries": "Batatas fritas",
    "click_to_select_app": "Clique para selecionar a partir da lista completa de aplicações",
    "consumer_persona": "Personalidade do consumidor",
    "to_enjoy_ar_title": "Para desfrutar da experiência de realidade aumentada, siga estes simples passos:",
    "maintain_good_lighting": "Manter uma boa iluminação",
    "avoid_direct_sunlight": "Evitar a luz solar direta",
    "avoid_cluttered_space": "Evitar espaços desordenados",
    "keep_two_feet_distance": "Manter pelo menos 60 cm de distância",
    "consumers_who_find": "Consumers who find",
    "appealing_text": "`appealing also show great interest to trying out savory foods in this color. They are usually females and see themselves as very adventurous when it come to trying unfamiliar food. When it comes to priorities regarding food, they enjoy culinary exploration and trying new flavours, cuisines and ingredients.`",
    "top_5_emotions": "As cinco principais emoções que os consumidores associam a esta cor",
    "color_n_flovor": "Intensidade da cor e do sabor",
    "color_intensity": "Intensidade da cor",
    "consumer_rank": "30% dos consumidores globais classificam",
    "top_3_preferred_color": "como as três cores favoritas, eles terão mais interesse em comprar se estiverem procurando uma experiência alimentar nova ou experimental.",
    "they_associate": "Eles associam",
    "color_savory_food": "alimentos saborosos e coloridos até sabores de beterraba, morango, pimenta, frutas vermelhas e framboesa.",
    "get_full_access": "Obter acesso total",
    "contact_us": "Contactar-nos",
    "logout": "Terminar sessão",
    "choose_your_language": "Escolha o seu idioma preferido",
    "confirm": "Confirmar",
    "please_fill_out_form": "Entre com seus dados para ter acesso a informações de consumidores e explorar o mundo das cores naturais através da realidade aumentada",
    "full_access_ques1": "Está atualmente utilizando corantes naturais?",
    "full_access_ques2": "Tem interesse em utilizar corantes naturais nos seus produtos?",
    "full_access_ques3": "Está procurando um fornecedor alternativo de corantes naturais?",
    "full_access_ques4": "Quais são as suas áreas de interesse? Seleccione todas as que se aplicam.",
    "full_access_ques5": "Quais são os desafios que enfrenta atualmente? Seleccione todos os que se aplicam.",
    "yes": "Sim",
    "no": "Não",
    "new_product_ideas": "Novas ideias de produtos",
    "color_solutions": "Soluções de cores que podem oferecer tonalidades únicas",
    "market_trends": "Tendências de mercado e insights do consumidor",
    "replacing_artificial_colors": "Substituindo cores artificiais por cores naturais",
    "Stability": "Estabilidade e prazo de validade de cores naturais",
    "value_to_brand": "Como as cores naturais podem agregar valor à sua marca",
    "other": "Outros (especifique)",
    "type_here": "Digite aqui",
    "do_not_know_about_colors": "Não sei nada sobre cores naturais",
    "need_help_about_colors": "Preciso de ajuda técnica usando cores naturais",
    "need_help_with_compliance": "Preciso de ajuda com conformidade regulatória em todos os mercados", 
    "how_to_choose_color": "Como escolher uma cor que agrade aos consumidores e atenda às expectativas de sabor",
    "need_market_and_consumers": "Preciso de insights do mercado e do consumidor para me ajudar em minhas decisões de negócios",
    "appealing": "Atraente",
    "neutral": "Neutro",
    "unappealing": "Não atraente",
    "home": "Início",
    "full_access_thank_you": "em contato em breve. Enquanto isso, verifique o seu correio eletrônico para ver a senha."
  }
};

export const getText = (text, defaultLang = '') => {
  let lang = localStorage.getItem('language') ?? 'EN';
  if (defaultLang) lang = defaultLang;
  const fallbackLang = lang === 'undefined' ? 'EN' : lang;
  return LANGUAGES[fallbackLang][text] ?? LANGUAGES['EN'][text];
};
