export const LANGUAGES = {
  EN: {
    building_a: 'Building a',
    sustainable: 'Sustainable',
    future: 'Future',
    enter_with_passcode: 'Enter with Passcode',
    enter_as_guest: 'Enter as a Guest',
    welcome: 'Welcome !',
    enter_passcode_to_access: 'Enter your email address and passcode to access',
    fill_in_details:
      'Fill in your details below to gain access to consumers insights and explore the world of natural colors',
    back: 'Back',
    name: 'Name',
    email: 'Email',
    submit: 'Submit',
    passcode: 'Passcode',
    phone: 'Phone no.',
    position: 'Position',
    company: 'Company',
    country: 'Country',
    interested_apps: 'Interested Key Applications',
    i_agree_to: 'I agree to the',
    privacy_policy: 'Privacy Policy',
    applications: 'Applications',
    language: 'Language',
    next: 'Next',
    beverage: 'Beverage',
    confectionary: 'Confectionery',
    dairy_n_fruit: 'Dairy & Fruit Preparation',
    ice_creme: 'Ice Cream',
    bakery_n_cereals: 'Bakery & Cereals',
    savory_n_meat: 'Savory & Meat',
    plant_based: 'Plant-based',
    pet_food: 'Pet Food',
    none: 'None',
    consumer: 'Consumer',
    emotion: 'Emotion',
    flavor: 'Flavor',
    intensity: 'Intensity',
    solution: 'Solution',
    choose_app: 'Choose one application',
    burger_bun: 'Burger Bun',
    dumpling: 'Dumpling',
    puff_snacks: 'Puff Snacks',
    noodle: 'Noodle',
    burger_sauce: 'Burger Sauce',
    salad_dressing: 'Salad Dressing',
    savory_dip: 'Savory Dip',
    nugget: 'Nugget',
    potato_chip: 'Potato Chip',
    french_fries: 'French Fries',
    click_to_select_app: 'Click to select from full list of applications',
    consumer_persona: 'Consumer Persona',
    to_enjoy_ar_title:
      'To enjoy the augmented reality experience, please follow these simple steps:',
    maintain_good_lighting: 'Maintain good lighting',
    avoid_direct_sunlight: 'Avoid direct sunlight',
    avoid_cluttered_space: 'Avoid cluttered spaces',
    keep_two_feet_distance: 'Keep at least 2 feet of distance',
    consumers_who_find: 'Consumers who find',
    appealing_text: `appealing also show great interest to trying out savory foods in this color. They are usually females and see themselves as very adventurous when it come to trying unfamiliar food. When it comes to priorities regarding food, they enjoy culinary exploration and trying new flavours, cuisines and ingredients.`,
    top_5_emotions: 'Top five Emotions consumers associate with this color',
    color_n_flovor: 'Color & Flavor Association',
    color_intensity: 'Color Intensity',
    consumer_rank: '30% of global consumers rank',
    top_3_preferred_color:
      'as their top 3 most preferred color that will interest them the most to buy if they are looking for a novel or experimental food experience.',
    they_associate: 'They associate',
    color_savory_food:
      'colored savory food to beetroot, strawberry, chilli, red dragonfruit and raspberry flavours.',
    get_full_access: 'Get Full Access',
    contact_us: 'Contact Us',
    logout: 'Logout',
    choose_your_language: 'Choose your preferred language',
    confirm: 'Confirm',
  },
  CMN: {
    building_a: '建设一个',
    sustainable: '可持续的',
    future: '未来',
    enter_with_passcode: '使用密码输入',
    enter_as_guest: '以访客身份进入',
    welcome: '欢迎 ！',
    enter_passcode_to_access: '输入您的电子邮件地址和密码进行访问',
    fill_in_details:
      '请在下面填写您的详细信息，以获得消费者见解并探索天然色素的世界',
    back: '后退',
    name: '姓名',
    email: '电子邮件',
    submit: '提交',
    passcode: '密码',
    phone: '电话号码',
    position: '位置',
    company: '公司',
    country: '国家',
    interested_apps: '感兴趣的关键应用',
    i_agree_to: '我同意',
    privacy_policy: '隐私政策',
    applications: '运用',
    language: '语言',
    next: '下一个',
    beverage: '饮料',
    confectionary: '糖果点心',
    dairy_n_fruit: '乳制品和水果制备',
    ice_creme: '冰淇淋',
    bakery_n_cereals: '面包店和谷物',
    savory_n_meat: '咸味和肉类',
    plant_based: '植物性',
    pet_food: '宠物食品',
    none: '没有任何',
  },
  SPA: {
    building_a: 'Construyendo un',
    sustainable: 'Sostenible',
    future: 'Futuro',
    enter_with_passcode: 'Ingrese con contraseña',
    enter_as_guest: 'Entra como invitado',
    welcome: 'Bienvenido !',
    enter_passcode_to_access:
      'Ingrese su dirección de correo electrónico y contraseña para acceder',
    fill_in_details:
      'Complete sus datos a continuación para obtener acceso a las opiniones de los consumidores y explorar el mundo de los colores naturales.',
    back: 'Atrás',
    name: 'Nombre',
    email: 'Correo electrónico',
    submit: 'Entregar',
    passcode: 'Código de acceso',
    phone: 'Número de teléfono.',
    position: 'Puesto',
    company: 'Compañía',
    country: 'País',
    interested_apps: 'Aplicaciones clave interesadas',
    i_agree_to: 'Estoy de acuerdo con el',
    privacy_policy: 'política de privacidad',
    applications: 'Aplicaciones',
    language: 'Idioma',
    next: 'Próxima',
    beverage: 'Bebida',
    confectionary: 'Confitería',
    dairy_n_fruit: 'Preparación de lácteos y frutas',
    ice_creme: 'Helado',
    bakery_n_cereals: 'Panadería y Cereales',
    savory_n_meat: 'Salados y Carnes',
    plant_based: 'A base de plantas',
    pet_food: 'Comida para mascotas',
    none: 'Ninguno',
  },
};

export const getText = (text) => {
  const lang = localStorage.getItem('language') || 'EN';
  return LANGUAGES[lang][text] ?? LANGUAGES['EN'][text]
};
